### ISSUE TITLE
slurm support

### ISSUE THREAD

**Issue by jos4uke** [apetkau/orthomcl-pipeline#12]
Hi
I would like to know if slurm is supported as a scheduler? Currently you mention sge or fork as an option value. Is sge option is compatible with slurm?

Thanks

Joseph

**Comment by apetkau** [comment]
Hello Joseph,

Support for sge is handled through the Perl module [Schedule::DRMAAc](http://search.cpan.org/~tharsch/Schedule-DRMAAc-0.81/Schedule_DRMAAc.pod), which is a Perl wrapper around the C bindings of DRMAA <https://en.wikipedia.org/wiki/DRMAA> used to submit jobs to a variety of cluster or grid computing schedulers.

There is an implementation available for SLURM <http://apps.man.poznan.pl/trac/slurm-drmaa> which, once built, may let you build the Perl module `Schedule::DRMAAc` against it to connect the OrthoMCL pipeline to SLURM (you'd still use the `sge` scheduler option).

I haven't attempted this though so don't have too much of an idea of how difficult it would be, but it's at least possible.

Let me know if you have any more questions,

Aaron

**Comment by apetkau** [comment]
I am going to close this issue, but if you do have other questions feel free to re-open it.
