### ISSUE TITLE
Suggestion : Update to use blast+

### ISSUE THREAD

**Issue by michoug** [apetkau/orthomcl-pipeline#13]
Hi
The legacy blast (blastall, formatdb) is being updated anymore.
I would suggest to update the requirement to the blast+ software
Best
Greg

**Comment by apetkau** [comment]
Hello Greg,

Thanks for the suggestion.  blast+ uses slightly different commands to legacy blast, and I'm uncertain if or in what ways the output format has changed.  Based on previous issues (https://github.com/apetkau/orthomcl-pipeline/issues/7) the specific version of blast can affect the results.  I will keep this in mind but I will be unlikely to get around to testing out updating to blast+ any time in the near future.  I am closing this issue for now but I welcome any other issues you may have.

Aaron
