### ISSUE TITLE
Error while connection with db 

### ISSUE THREAD

**Issue by shrutidabral** [apetkau/orthomcl-pipeline#14]
hello ,

Can you you please help to figure out whats wrong with Orthomcl databse connection??

error is----- 
Connecting to mysql and creating database orthomcl1 on host localhost with user sdabral@cdslifesciences.com ...
DBI connect('mysql:localhost:mysql_local_infile=1','sdabral@cdslifesciences.com',...) failed: Access denied for user 'sdabral@cdslifesciences.com'@'localhost' (using password: YES) at ./orthomcl-setup-database.pl line 89.
error connecting to database at ./orthomcl-setup-database.pl line 93.

**Comment by apetkau** [comment]
I'm guessing you figured it out?  Thanks for closing :smile:.  If you have any other issues just let me know.

**Comment by shrutidabral** [comment]
Yup , that was something stupid error . 
 if i get some issues again then definitely I will post it. 

Thank you .

**Comment by xiao7462** [comment]
i met the same problem ,can you tell me how to figured it out?

**Comment by apetkau** [comment]
Can you try logging in directly with the `mysql` command?  E.g.,

```
mysql -u orthomcl -p
```

If you can log in with the same credentials then this rules out the possibility of invalid credentials.

**Comment by xiao7462** [comment]
Thank you very much! installing is ok ,but i use `./bin/orthomcl-pipeline`, i get `./bin/orthomcl-pipeline: line 11: /data1/XXX/software/orthomcl-pipeline/bin/../scripts/orthomcl-pipeline.pl: Permission denied`

**Comment by apetkau** [comment]
Did running `perl scripts/orthomcl-pipeline-setup.pl` succeed? https://github.com/apetkau/orthomcl-pipeline/blob/master/INSTALL.md#step-2-other-dependencies

This should write a file for you, `bin/orthomcl-pipeline`.  Does this file exist?

**Comment by pascalan** [comment]
Hi, 
I'm getting a similar error as Xiao7462, but I have the permission to execute orthomcl-pipeline.pl.

$ perl t/test_pipeline.pl -m orthomcl.conf -s fork -t /tmp
Test using scheduler fork

TESTING NON-COMPLIANT INPUT
TESTING FULL PIPELINE RUN 1
README:
Test using with no splitting of fasta files.
Could not execute command /Users/pascal/bioinformatics/orthomcl-pipeline/t/../bin/orthomcl-pipeline --nocompliant --scheduler fork --yes -c /Users/pascal/bioinformatics/orthomcl-pipeline/t/data/basic/1/etc/orthomcl-pipeline.conf -i /Users/pascal/bioinformatics/orthomcl-pipeline/t/data/basic/1/input -o /tmp/orthomcl-pipeline.g_oG2C/output -m /tmp/orthomcl-pipeline.g_oG2C/orthomcl.config 2>/tmp/orthomcl-pipeline.g_oG2C/orthomcl-pipeline.err.log 1>/tmp/orthomcl-pipeline.g_oG2C/orthomcl-pipeline.out.log

Can you you please help to figure out what's wrong?

perl scripts/orthomcl-pipeline-setup.pl was successful. I'm working on a Mac OS Mojave 10.14.3.

**Comment by apetkau** [comment]
@pascalan I'm glad you solved it :smile:. If you do have other issues though, could you please open up a new issue on github? Thanks.

**Comment by niconm89** [comment]
Hi, sorry for the comment here (clossed issue) but I think my problem is close related with the discussion.

I'm trying to install orthomcl-pipeline on Ubuntu 20.04. I have installed a conda environment with all dependencies.
I also created both user and database for orthomcl and grant all privileges. I'm able to access to the orthomcl user for mysql using the command:

`mysql -u orthomcl -h localhost orthomcl -p`

but...when I try to setup the database running the script orthomcl-setup-database.pl , I get the following error:
```
perl scripts/orthomcl-setup-database.pl --user orthomcl --password orthomcl --host localhost --database orthomcl --outfile orthomcl.conf --no-create-database
Connecting to database orthomcl on host localhost with user orthomcl2 ...
DBI connect('orthomcl:localhost:mysql_local_infile=1','orthomcl2',...) failed: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2) at scripts/orthomcl-setup-database.pl line 71.
error connecting to database (please ensure database exists and try again) at scripts/orthomcl-setup-database.pl line 75.
```

I checked all dependencies and reinstall DBD:MySQL and DBI perl packages, and testing works!
Do you have any idea how to fix this?

Nicolás

**Comment by apetkau** [comment]
Hello @niconm89 

Do you know why it says `Connecting to database orthomcl on host localhost with user orthomcl2 ...` or was that text from a different attempt (since it looks like the proper user is `orthomcl`).

You could try to connect to `127.0.0.1` instead of `localhost` to force a connection via TCP/IP (https://stackoverflow.com/a/16402615).

**Comment by niconm89** [comment]
Hi @apetkau , thanks for your reply. The difference in user name was a typing error when I wrote the command here. The user name actually is orthomcl2.
The change you suggested works! Thanks a lot, using 127.0.0.1 I was able to connect to the MySQL database.

Best,

Nicolás

**Comment by mexe27** [comment]
Hi @apetkau 

I am also sorry for the comment, but I'm a little frustrated with an error when I try to run `orthomclInstallSchema orthomcl.config` . I installed MySQL (Server version: 8.0.32-0ubuntu0.20.04.2 (Ubuntu)) locally and I created a user and DB called orthomcl. I can enter the server with no problem with: ` mysql -u orthomcl -ppassword -h localhost` and I can visualize the DB:

mysql> SHOW DATABASES;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| orthomcl           |
| performance_schema |
+--------------------+
3 rows in set (0.01 sec)

But when I run `orthomclInstallSchema orthomcl.config` I get: " illegal line in config file 'dbLogin=' "... seems that the printed error comes from "OrthoMCLEngine::Main::Base" but I really don't know how to resolve it. My orthomcl.config is:

 this config assumes a mysql database named 'orthomcl'.  adjust according
 to your situation.
dbVendor=mysql
dbConnectString=dbi:mysql:orthomcl:localhost:3306
dbLogin=orthomcl
dbPassword=password
similarSequencesTable=SimilarSequences
orthologTable=Ortholog
inParalogTable=InParalog
coOrthologTable=CoOrtholog
interTaxonMatchView=InterTaxonMatch
percentMatchCutoff=50
evalueExponentCutoff=-5
oracleIndexTblSpc=NONE

Could it be something related to dbConnectString??

Thank you in advance.

**Comment by mexe27** [comment]
I am so sorry. I was able to resolve this. I realized a dumb mistake with my orthomcl.config...

Thank you anyway :)

**Comment by apetkau** [comment]
@mexe27 I'm glad you were able to get everything resolved 😄
