### ISSUE TITLE
MSG: The sequence does not appear to be FASTA format (lacks a descriptor line '>')

### ISSUE THREAD

**Issue by wangzhennan14** [apetkau/orthomcl-pipeline#15]
Hi,
    When I use orthomcl-pipeline to deal with some fasta files, there were some errors, like this:
    MSG: The sequence does not appear to be FASTA format (lacks a descriptor line '>')
    What is the matter? The fasta file I have valided, and it was correct. Can you give me some advice to solve this? Thank you very much!

                                                                                                                           Wang

**Comment by apetkau** [comment]
When you say the files were valid do you mean the pipeline made it all the way through **State 1: Validate Files** without any errors?  What stage are you seeing this error?

Do you think you could paste in the messages  you get when you are running the pipeline?

**Comment by apetkau** [comment]
I am closing this issue.  If it is still a problem you may re-open it.
