### ISSUE TITLE
YAML/Tiny.pm preventing set-up

### ISSUE THREAD

**Issue by abbyhudak** [apetkau/orthomcl-pipeline#16]
When trying to run orthomcl-pipeline-setup.pl, the error message says: Can't locate YAML/Tiny.pm in @INC (you may need to install the YAML::Tiny module).  When I try to install this module it fails at installing another module, Devel::Leak::Module and therefore cannot get get the YAML: Tiny module to install.

**Comment by abbyhudak** [comment]
I am using perl5.  I am not getting an error like the one you used as an example.  It just says @INC contains: and the pathways.  I am not sure why only this one module is having issues. Do you know if there is something on my end I can do to modify the INC so it can find the module?

________________________________

**Comment by apetkau** [comment]
Well, if the module fails to install then it may not work correctly even if you do add a path to **@INC**.  You could try to install with `cpanm --force YAML::Tiny` though to force install even when something failed.

Another option is to use a [conda](https://conda.io/docs/) environment to install and manage a separate version of Perl and all modules.

You can do this by first downloading and installing conda (https://conda.io/miniconda.html) then running

```
conda create --name orthomcl -c defaults -c conda-forge -c bioconda perl perl-app-cpanminus
```

Then, to work with the **orthomcl** environment and attempt to install YAML::Tiny you could run:

```
source activate orthomcl
cpanm YAML::Tiny
```

More information on conda and conda environments can be found at https://conda.io/docs/user-guide/getting-started.html#managing-environments.  Also, you may want to check out [bioconda](https://bioconda.github.io/) for many conda packages related to bioinformatics.

**Comment by apetkau** [comment]
I am closing this issue.  If this is still a problem you may re-open it.

**Comment by dtx282000** [comment]
Hi, I have faced the same question. the error is as follows:
Can't locate YAML/Tiny.pm in @INC (you may need to install the YAML::Tiny module) (@INC contains: /home/dengtx/software/mirdeep2/lib/perl5/x86_64-linux-gnu-thread-multi /home/dengtx/software/mirdeep2/lib/perl5 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at scripts/orthomcl-pipeline-setup.pl line 6.
BEGIN failed--compilation aborted at scripts/orthomcl-pipeline-setup.pl line 6.

Actually, I have successfully installed the  YAML::Tiny module with the command line of cpanm --force YAML::Tiny. Now, I have no idea how to deal with it.

**Comment by amymariecampbell** [comment]
@dtx282000 Did you ever find a solution to this?
