### ISSUE TITLE
DBD::mysql::st execute failed: Error on rename of './orthomcl/#sql-616f_3e660.MYI' to './orthomcl/SimilarSequencess.MYI' (Errcode: 2)

### ISSUE THREAD

**Issue by tiramisutes** [apetkau/orthomcl-pipeline#17]
Dear,
I install the orthomcl-pipeline as suggest in [Installing](https://github.com/apetkau/orthomcl-pipeline/blob/master/INSTALL.md) page. But there is some error stdout when run.

```
DBD::mysql::st execute failed: Error on rename of './orthomcl/#sql-616f_3e660.MYI' to './orthomcl/SimilarSequencess.MYI' (Errcode: 2)
```
I have google for this question but not have a good solution?
Any help is much appreciated.
Thanks.

**Comment by apetkau** [comment]
Do you get this error when going through the installation instructions?  Or when you run OrthoMCL on some data?  What version of database software are you using (e.g., https://stackoverflow.com/questions/8987679/how-to-retrieve-the-current-version-of-a-mysql-database).

According to https://stackoverflow.com/questions/160233/what-does-mysql-error-1025-hy000-error-on-rename-of-foo-errorno-150-me errors similar to this come up when renaming keys in the database.  I'm not sure exactly why you're getting the message above, but you could you try dropping/re-creating the `orthomcl` database?  That is:

```
drop database orthomcl;
```

Then re-running the `orthomcl-setup-database.pl` script (https://github.com/apetkau/orthomcl-pipeline/blob/master/INSTALL.md#step-3-database-setup).

**Comment by tiramisutes** [comment]
As your suggestion, I find the orthomcl database and SimilarSequencess table that maybe create by someone who has used it.  But I can not delete this orthomcl database maybe because of permission denied. I'm not root user;
Then I try to create a new database but still can't successful operation.
```
+--------------------+
| Tables_in_orthomcl |
+--------------------+
| SimilarSequencess  |
+--------------------+
1 row in set (0.01 sec)

mysql> drop database orthomcl;
ERROR 1010 (HY000): Error dropping database (can't rmdir './orthomcl', errno: 39)
mysql> 
```

**Comment by apetkau** [comment]
If you have the ability to create a new database are you able to grant permissions to that database for the orthomcl user - <https://github.com/apetkau/orthomcl-pipeline/blob/master/INSTALL.md#step-3-database-setup>?  You could try that to use a completely new database.

Otherwise, you would likely have to ask whoever has root permissions to clear out the old orthomcl database and/or create a new one for you.

You could also try clearing out some of the tables in the orthomcl database without dropping the database (e.g., https://stackoverflow.com/questions/3476765/mysql-drop-all-tables-ignoring-foreign-keys), but I have never tried that so I'm not sure how well it would work.

**Comment by tiramisutes** [comment]
I create a completely new database and run this pipeline again. But I still have stderr.
```
$ perl scripts/orthomcl-setup-database.pl --user orthomcl --password orthomcl --host localhost --database Neworthomcl --outfile orthomcl.conf
Connecting to mysql and creating database Xorthomcl on host node62 with user genome ...
OK
database Neworthomcl created ...OK
Config file orthomcl.conf created.
```
But It still not works when I run the `test_pipeline.pl`.
```
$ perl t/test_pipeline.pl -m orthomcl.conf -s fork -t /tmp
Test using scheduler fork

TESTING NON-COMPLIANT INPUT
TESTING FULL PIPELINE RUN 1
README:
Test using with no splitting of fasta files.
Could not execute command /public/home/software/orthomcl-pipeline/t/../bin/orthomcl-pipeline --nocompliant --scheduler fork --yes -c /public/home/software/orthomcl-pipeline/t/data/basic/1/etc/orthomcl-pipeline.conf -i /public/home/software/orthomcl-pipeline/t/data/basic/1/input -o /tmp/orthomcl-pipeline.NGQzn2/output -m /tmp/orthomcl-pipeline.NGQzn2/orthomcl.config 2>/tmp/orthomcl-pipeline.NGQzn2/orthomcl-pipeline.err.log 1>/tmp/orthomcl-pipeline.NGQzn2/orthomcl-pipeline.out.log
```
Then I check the stderr.log and find the same as I use old database.
```
DBD::mysql::st execute failed: Error on rename of './Neworthomcl/#sql-616f_712f6.MYI' to './Neworthomcl/SimilarSequences.MYI' (Errcode: 2)
```

**Comment by apetkau** [comment]
You may want to try the command `GRANT ALL PRIVILEGES ON Neworthomcl.* to 'orthomcl'@'%'` and `GRANT ALL PRIVILEGES ON Neworthomcl.* to 'orthomcl'@'localhost'`, just in case there is some permission the `orthomcl` user is not being granted from the previous commands.
