### ISSUE TITLE
Can't set up a new mysql user count 

### ISSUE THREAD

**Issue by xiao7462** [apetkau/orthomcl-pipeline#18]
When i type `mysql> GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, CREATE VIEW, INDEX, DROP on *.* to orthomcl;`   by logging into the MySQL server as root
i get `ERROR 1133 (42000): Can't find any matching row in the user table` 

type `flush privileges;` doesn't work

**Comment by apetkau** [comment]
There is likely no `orthomcl` user set up in your database.  You will have to run `create user 'orthomcl'@'localhost' identified by 'password';` first - https://dev.mysql.com/doc/refman/8.0/en/create-user.html#create-user-overview
