### ISSUE TITLE
error in setp 10 when i run the orthomcl-pipeline with sge scheduler

### ISSUE THREAD

**Issue by fyymxb** [apetkau/orthomcl-pipeline#19]
Hello, 
  I meet some error when i run the orthomcl-pipeline with sge scheduler.

  In the log folder, I get something like these:
      orthomclDumpPairs.log
      11.orthomclPairs.log.stderr
      11.orthomclPairs.log
      11.orthomclPairs.log.stdout
      10.orthomclLoadBlast.err.log
      10.orthomclLoadBlast.out.log
      9.parseBlast.log
      blast
      formatdb.log
     7.format-stderr.log
     7.format-stdout.log
     split.log
     filterFasta.log
     adjustFasta.log
     3.loadschema.stderr.log
     3.loadschema.stdout.log
     run.properties

  In the 10.orthomclLoadBlast.err.log file, I got the error message:
      DBI connect('orthomcl:localhost:mysql_local_infile=1','orthomcl',...) failed: Can't connect to local   MySQL server through socket '/var/lib/mysql/mysql.sock' (2) at /share/nas1/xub/softwares/anaconda3/bin/../lib/perl/OrthoMCLEngine/Main/Base.pm line 56.
 
   There are 1 manager node, 1 storage node and 3 compute nodes in my cluster. In the manager node, I can connect to the mysql with "mysql -uorthomcl -porthomcl" command; and in the compute node, I can connect to the mysql with "mysql -h ip -uorthomcl -porthomcl" command.
 Does this error mean that i should install and configure another mysql sever in all compute nodes? or  have I make some other mistakes?
 
Any help is much appreciated.
Thanks.

**Comment by apetkau** [comment]
No, you should not need to install and configure a mysql server for each compute node, each compute node should point to the same mysql server.

I think what's going on is that the orthomcl pipeline is configured to connect to a database on `localhost`, which does not exist for the compute nodes.  You can fix this by passing `--host [hostname/ip address]` when you run `orthomcl-setup-database.pl`, where `[hostname/ip address]` is the address of the database server that is visible to the compute nodes.

Alternatively, you can open up the **orthomcl.conf** file and change `localhost` to the proper address (https://github.com/apetkau/orthomcl-pipeline/blob/master/INSTALL.md#step-3-database-setup).

**Comment by fyymxb** [comment]
Hello, 
 The pipeline works.
 Thank you very much!
