### ISSUE TITLE
groups datafile further analysis

### ISSUE THREAD

**Issue by wenjingcui** [apetkau/orthomcl-pipeline#20]
hi there,
thanks a lot! it is a very useful and powerful pipeline!
i used ur pipeline to analysed my genome(5 strains) data and get a result file named groups.txt, i want to know how to understand this file, coz i want to get  a core gene set and the accessary genome detail(strain specific gene+shared by several strains),could you give me some advise? how can i get these results?
I am looking forward to your reply! I would be grateful to all your kindness!
best regards!
wenjing cui

**Comment by apetkau** [comment]
Thank you.

If you haven't seen it already, you can follow through the tutorial in https://github.com/apetkau/microbial-informatics-2014/tree/master/labs/orthomcl, specifically https://github.com/apetkau/microbial-informatics-2014/tree/master/labs/orthomcl#step-7-looking-at-the-results, which should help you to understand what sort of results you can get from OrthoMCL.  The main page contains more information on where to download example data https://github.com/apetkau/microbial-informatics-2014.

**Comment by wenjingcui** [comment]
that helps a lot! thanks a lot sir!

**Comment by wenjingcui** [comment]
i tried used your scripts. Thare  are still some problems i  cann't solve.
is your script can only analysis three set of groups? when i  set my genome groups into 5 it can not work; when i set it to  it works, it gives me a three group files , but the venn Diagram show no core genes, i am so confused coz i can clearly see thare a lot of core genes in the group.txt file, how can i fix this?
And, do the multiple-copy of gene in some strains influence the output result?
i know it's a little rude to write to u  so frequently, but i have no one to ask help for this, could u  do me a favor?
best regards!

**Comment by wenjingcui** [comment]
hi sir,
I have sucessfully running your scripts. but where can i found the core gene set?
my final resulr txt like this:
Number of genes seen in the following genomes:
CCBAU83666: 6266
CCBAU25509: 6218
CCBAU45436: 6097
CCBAU05684: 4798
CCBAU05631: 5411
Total genes seen: 28790
'Core' gene sets that is contained: 5 genomes has 3697 genes.
so where can i find these core gene set?

**Comment by apetkau** [comment]
That's great.  I'm glad you got everything working.  The script `nml_parse_orthomcl.pl` will mostly print out a summary and draw a Venn Diagram.  If you want the exact list of core genes, you could extract it directly from the **groups.txt** file.

The file `groups.txt` is formatted like:

```
group_1: Genome1|geneA Genome2|geneA Genome3|geneA
group_2: Genome1|geneB Genome2|geneB Genome3|geneB
...
```

Each line **group_X** lists a group of related (homologous) genes, separate by spaces.  In this case, **group_1** contains the genes *Genome1|geneA*, *Genome2|geneA*, *Genome3|geneA*; **group_2** contains the genes *Genome1|geneB*, *Genome2|geneB*, *Genome3|geneB*.

The total number of lines in `groups.txt` correspond to the total number of groups (or clusters) of homologous genes. This will contain all core genes, but can also contain accessory genes (e.g., where only 4 of your 5 genomes have a homologous gene).

To extract all core genes, you want to extract all lines in `groups.txt` where all of your genomes are present.  You could do this with `grep`, e.g., with:

```
cat groups.txt | grep Genome1 | grep Genome2 | grep Genome3
```

In your case, you could run:

```
cat groups.txt | grep CCBAU83666 | grep CCBAU25509 | grep CCBAU45436 | grep CCBAU05684 | grep CCBAU05631
```

This should leave you with only those lines in `groups.txt` containing all your genomes (e.g., the core gene set).
