### ISSUE TITLE
How to continue when the orthomcl-pipeline breaked in one step?

### ISSUE THREAD

**Issue by wangzhennan14** [apetkau/orthomcl-pipeline#22]
Hi,
    When I run orthomcl-pipeline, it breaked on step 10. I have resolved the problem, but I don't know how to run it from step10. Can you tell me how to continue this pipeline from step10? Thank you very much!
                                                                                                                                                      Wang

**Comment by apetkau** [comment]
Hello Wang,

There is no way of continuing on from an intermediate step in this pipeline.  You could either re-run the whole pipeline, or you could take the intermediate data and follow along with the original OrthoMCL instructions (http://orthomcl.org/common/downloads/software/v2.0/UserGuide.txt).  **Step 10** in the `orthomcl-pipeline` corresponds to **Step 9: orthomclLoadBlast** in the original OrthoMCL instructions (the input file would be a file named `similarSequences.txt` here).

Aaron

**Comment by wangzhennan14** [comment]
Hi,
    Thank you very much!
                                                          Wang
