### ISSUE TITLE
=Stage 1: Validate Files =

### ISSUE THREAD

**Issue by gumingjian1** [apetkau/orthomcl-pipeline#24]
Hi，
I met a mistake, how can I fix it? Thanks!!!
=Stage 1: Validate Files =
Error: file /home/guming/test_data/zbl/U.fasta contains invalid header for "lcl|CP017025.1_prot_AOH49748.1_1": files not marked as compliant but found compliant header.
Perhaps try removing --nocompliant, or checking files. at /home/guming/orthomcl/bin/../scripts/orthomcl-pipeline.pl line 334, <GEN0> line 1.
Validating U.fasta ... [guming@localhost orthomcl]$

**Comment by gumingjian1** [comment]
[U.fasta.zip](https://github.com/apetkau/orthomcl-pipeline/files/2436201/U.fasta.zip)

**Comment by gumingjian1** [comment]
> Hello @gumingjian1. The error is related to the sequence identifier in the fasta files which look like
> 
> ```
> >lcl|CP017025.1_prot_AOH49748.1_1 [gene=waaV] [locus_tag=CC14983A_0628] [protein=glycosyltransferase, family 2] [protein_id=AOH49748.1] [location=640667..641476] [gbkey=CDS]
> ```
> 
> OrthoMCL uses the `|` character to differentiate the protein/gene id from the taxon/organism id. This conflicts with the existing usage of this character.
> 
> The easiest fix is to replace all instances of this character with something else (such as `_`) before passing your fasta files into OrthoMCL. This could be done with the `sed` command as follows:
> 
> ```
>  sed -i.bak -e 's/|/_/g' U.fasta
> ```
> 
> This will change `>lcl|CP017025.1_prot_AOH49748.1_1` to `>lcl_CP017025.1_prot_AOH49748.1_1`.
> 
> I hope this helps you out.

Wa，it works! I really appreciate your kind help!!!

**Comment by apetkau** [comment]
No problem. Let me know if you have any more questions.
