### ISSUE TITLE
Error in test, step 3

### ISSUE THREAD

**Issue by jsoghigian** [apetkau/orthomcl-pipeline#26]
Hi,

I'm receiving an error in step3 during testing. It seems to be related to DBD::mysql not being found, despite the fact it is installed.  I am wondering if it is due to me using perlbrew to have perl 5.28 active, but I am not certain since other modules are being found just fine.

Command:
perl t/test_pipeline.pl -m orthomcl.conf -s fork -t /tmp

The file 3.loadschema.stderr contains the following:

> Can't locate DBD/mysql.pm in @INC (you may need to install the DBD::mysql module) (@INC contains: /Users/phelix/apps/orthomclsoftware-custom/bin/../lib/perl /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2/darwin-thread-multi-2level /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /Users/phelix/apps/orthomclsoftware-custom/bin/../lib/perl/OrthoMCLEngine/Main/Base.pm line 51, <F> line 12.

But if I try to install DBD::mysql I am told it is up to date.  If I turn off perlbrew, I am instead told other modules can't be located and that is very early on.

**Comment by jsoghigian** [comment]
Figured it out...

By updating orthomclInstallSchemafrom (from orthoMCL) from #!/usr/bin/perl to #!/usr/bin/env perl I completed step 3.  I hit a similar error in step 10, and so I updated the perl scripts in the orthomcl bin directory similarly.

Now I've run into the 'dreaded' command not allowed with mysql version, so I will address that as per the other issues here. 

Closing this comment.

**Comment by apetkau** [comment]
I'm glad you figured it out 😄. Thanks for closing the issue.
