### ISSUE TITLE
Re-run orthoMCL-pipeline from a given stage ?

### ISSUE THREAD

**Issue by BiodivGenomic** [apetkau/orthomcl-pipeline#27]
Hello,
is it possible to re-run orthoMCL-pipeline from a given step ? The pipeline failed after the BLAST, that is obviously the most time consuming step, so I would greatly prefer not to have to go through again...
Thanks in advance, Damien

**Comment by apetkau** [comment]
Hello,

No, there's no built-in way to re-run the pipeline from a given step. You could, in theory, take the BLAST results you currently have and follow the original OrthoMCL instructions manually (http://orthomcl.org/common/downloads/software/v2.0/UserGuide.txt). But, there's no automated way to do this.

Aaron

**Comment by BiodivGenomic** [comment]
OK, thank you for your answer... it could be a nice improvement for a future version ;-)
