### ISSUE TITLE
Does the MySQL version have an impact on the results?

### ISSUE THREAD

**Issue by jingydz** [apetkau/orthomcl-pipeline#28]
Hello, when I was doing this process, I was always reporting the error at step 10, and my MySQL version started out with 5.5, and I saw someone saying it had to be 5.7.So I changed the version of MySQL from 5.5 to 5.6 and then to 5.7, but why is it always wrong at step 10?I wonder if there is any requirement for the version of MySQL.Besides, why is my tenth step wrong?

=Stage 10: Load Blast Results=
/data/users/zhangjingjing/OrthoMCL/orthomclSoftware-v2.0.9/bin/orthomclLoadBlast "/data/users/zhangjingjing/OrthoMCL/orthomcl-pipeline/scripts/orthomcl.conf" "/data/users/zhangjingjing/OrthoMCL/orthomcl-pipeline/ceshi11_out/blast_load/similarSequences.txt" 1>/data/users/zhangjingjing/OrthoMCL/orthomcl-pipeline/ceshi11_out/log/10.orthomclLoadBlast.out.log 2>/data/users/zhangjingjing/OrthoMCL/orthomcl-pipeline/ceshi11_out/log/10.orthomclLoadBlast.err.log
Error executing command: /data/users/zhangjingjing/OrthoMCL/orthomclSoftware-v2.0.9/bin/orthomclLoadBlast "/data/users/zhangjingjing/OrthoMCL/orthomcl-pipeline/scripts/orthomcl.conf" "/data/users/zhangjingjing/OrthoMCL/orthomcl-pipeline/ceshi11_out/blast_load/similarSequences.txt" 1>/data/users/zhangjingjing/OrthoMCL/orthomcl-pipeline/ceshi11_out/log/10.orthomclLoadBlast.out.log 2>/data/users/zhangjingjing/OrthoMCL/orthomcl-pipeline/ceshi11_out/log/10.orthomclLoadBlast.err.log. See logs /data/users/zhangjingjing/OrthoMCL/orthomcl-pipeline/ceshi11_out/log/10.orthomclLoadBlast.out.log and /data/users/zhangjingjing/OrthoMCL/orthomcl-pipeline/ceshi11_out/log/10.orthomclLoadBlast.err.log

**Comment by jingydz** [comment]
I would like to add the wrong report.[root@GenEngine zhangjingjing]# less /data/users/zhangjingjing/OrthoMCL/orthomcl-pipeline/ceshi11_out/log/10.orthomclLoadBlast.out.log
[root@GenEngine zhangjingjing]# less /data/users/zhangjingjing/OrthoMCL/orthomcl-pipeline/ceshi11_out/log/10.orthomclLoadBlast.err.log
DBD::mysql::st execute failed: Data too long for column 'SUBJECT_ID' at row 240 at /data/users/zhangjingjing/OrthoMCL/orthomclSoftware-v2.0.9/bin/orthomclLoadBlast line 39, <F> line 12.

**Comment by apetkau** [comment]
Thanks for providing the error file.

The following message from the `orthomclLoadBlast` program:

```
DBD::mysql::st execute failed: Data too long for column 'SUBJECT_ID'
```

makes me think that the error is related to the length of the sequence IDs in the original input FASTA files. The `SUBJECT_ID` column this is referring to is set here https://github.com/apetkau/orthomclsoftware-custom/blob/master/bin/orthomclInstallSchema#L50, where it is given a maximum length of 60 characters. If the FASTA sequence IDs end up greater than 60 characters, this would likely cause the issue you are encountering.

To fix this you could shorten the length of the IDs in the FASTA files. Or, you could change the maximum character limit in https://github.com/apetkau/orthomclsoftware-custom/blob/master/bin/orthomclInstallSchema#L50 (though for this to work, you'd likely have to change ever `sequence_id` character limit in that file to some value > 60).

I hope this helps you out.

**Comment by jingydz** [comment]
Sorry to bother you again!
But I have modified orthomcl software-v2.0.9/bin/Argument to line 50 in the orthomclinstallschema file.
I changed it from 60 to 200, but I had some problems.

**Comment by jingydz** [comment]
Sorry to bother you again!
But I have modified orthomcl software-v2.0.9/bin/Argument to line 50 in the orthomclinstallschema file.
I changed it from 60 to 200, but I had some problems.
 It's still going wrong at step 10.

[root@GenEngine orthomcl-pipeline]# less /data/users/zhangjingjing/OrthoMCL/orthomcl-pipeline/ceshi1_out/log/10.orthomclLoadBlast.out.log
[root@GenEngine orthomcl-pipeline]# less /data/users/zhangjingjing/OrthoMCL/orthomcl-pipeline/ceshi1_out/log/10.orthomclLoadBlast.err.log
DBD::mysql::st execute failed: Data too long for column 'QUERY_ID' at row 84726 at /data/users/zhangjingjing/OrthoMCL/orthomclSoftware-v2.0.9/bin/orthomclLoadBlast line 39, <F> line 12.
But my file only has 41060 lines, and how did this line 84726 come from?

**Comment by jingydz** [comment]
Sorry to bother you again!
But I have modified orthomcl software-v2.0.9/bin/Argument to line 50 in the orthomclinstallschema file.
I changed it from 60 to 200, but I had some problems.
 It's still going wrong at step 10.

[root@GenEngine orthomcl-pipeline]# less /data/users/zhangjingjing/OrthoMCL/orthomcl-pipeline/ceshi1_out/log/10.orthomclLoadBlast.out.log
[root@GenEngine orthomcl-pipeline]# less /data/users/zhangjingjing/OrthoMCL/orthomcl-pipeline/ceshi1_out/log/10.orthomclLoadBlast.err.log
DBD::mysql::st execute failed: Data too long for column 'QUERY_ID' at row 84726 at /data/users/zhangjingjing/OrthoMCL/orthomclSoftware-v2.0.9/bin/orthomclLoadBlast line 39, <F> line 12.
But my file only has 41060 lines, and how did this line 84726 come from?

**Comment by apetkau** [comment]
That's okay.

For that error, it looks like there's other columns where your FASTA sequence ids are too long (in this case the [QUERY_ID](https://github.com/apetkau/orthomclsoftware-custom/blob/master/bin/orthomclInstallSchema#L49)). You could try upping all `VARCHAR`s to 200 and seeing if this will work.

For the line number, this is referring to the file of BLAST results it is loading into the database. Since it's doing an all-vs-all BLAST, the number of lines in the blast results will be much greater than the number of lines in your file.

**Comment by jingydz** [comment]
Thank you very much for your answer!
