### ISSUE TITLE
orthomclpairs table lock size error

### ISSUE THREAD

**Issue by tuguangxian** [apetkau/orthomcl-pipeline#31]
hello,when I run stage 11: OrthoMCL Pairs=
orthomclSoftware-v2.0.9/bin/orthomclPairs "orthomcl-pipeline/orthomcl.conf" "/orthomcl/log/11.orthomclPairs.log" "cleanup=yes" 1>/orthomcl/log/11.orthomclPairs.log.stdout 2>/orthomcl/log/11.orthomclPairs.log.stderr

Output such an error:
DBD::mysql::st execute failed: The total number of locks exceeds the lock table size at /he_lab/share/data/local/orthomcl-pipeline/orthomclSoftware-v2.0.9/bin/orthomclPairs line 709, <F> line 12.

Can you give  me some suggestions and solutions? Thank you!

**Comment by apetkau** [comment]
Hello @tuguangxian. This thread may help you out https://www.biostars.org/p/163888/

Specifically, you could try setting [innodb_buffer_pool_size](https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_buffer_pool_size) to a larger size and restarting MySQL.

**Comment by tuguangxian** [comment]
Thank you very much @apetkau ! My problem was solved successfully! 
It's even better if you can set it in config when installing the orthomcl-pipeline.
Best wishes for you!

**Comment by apetkau** [comment]
No problem. Since this is a MySQL specific configuration it cannot be set in the config files when installing the pipeline, but at least it can be changed in MySQL.

I noticed you re-opened this. Was there still some issues you were encountering?

**Comment by wuxiaopei0509** [comment]
Hi, @apetkau 
sorry to bother you again. I have the same problem. I have 13 species and each haves about 25000~50000 proteins .How should I set the  innodb_buffer_pool_size ?

**Comment by apetkau** [comment]
Hello @wuxiaopei0509.

The innodb_buffer_pool_size is set in your MySQL/MariaDB/database configuration (https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_buffer_pool_size).

I unfortunately cannot help you to figure out what size to set it beyond to say that it should be increased to a higher value. It will likely require some trial and error to figure out the exact value.
