### ISSUE TITLE
error at orthomcl-setup-database step

### ISSUE THREAD

**Issue by naktang** [apetkau/orthomcl-pipeline#32]
I successful to install both orthomcl and orthomcl-pipeline by follow this link "http://darencard.net/blog/2018-01-12-orthomcl-tutorial/"

orthomcl.conf was create without any problem.

However, when I try to set up orthomcl database with the following command and it gave me an error

/usr/bin/perl /home/wat/Desktop/software/orthomcl-pipeline/scripts/orthomcl-setup-database.pl --user orthomcl_test --password password --host localhost --database orthomcl --outfile orthomcl.conf --no-create-database 

The error message was shown below.
Connecting to database orthomcl on host localhost with user orthomcl_test ...
DBI connect('orthomcl:localhost:mysql_local_infile=1','orthomcl_test',...) failed: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) at /home/wat/Desktop/software/orthomcl-pipeline/scripts/orthomcl-setup-database.pl line 71.
error connecting to database (please ensure database exists and try again) at /home/wat/Desktop/software/orthomcl-pipeline/scripts/orthomcl-setup-database.pl line 75.

Does anyone had the same problem. Any help would be appropriate.

**Comment by apetkau** [comment]
Are you able to connect to MySQL server using the `mysql` command with the same username and password? That is:

```bash
mysql -u orthomcl_test -ppassword --host localhost --database orthomcl
```

**Comment by naktang** [comment]
Yes I able to connect to MySQL server by using your giving command

mysql -u orthomcl_test -ppassword --host localhost --database orthomcl

**Comment by apetkau** [comment]
Okay, great.

I noticed you were running with `--no-create-database`, which means that `orthomcl-setup-database.pl` will not create the database for you. If it does not already exist you will have to create the database yourself by first logging into MySQL directly (as above) and running:

```sql
create database orthomcl;
```

If you don't do this, the above error is likely to display. Could you try this out?
