### ISSUE TITLE
error at Stage 10: Load Blast Results

### ISSUE THREAD

**Issue by U201412486** [apetkau/orthomcl-pipeline#33]
Hi,
  When I run orthmcl-pipeline at Stage 10: Load Blast Results,it reports the error below.
  `DBD::mysql::st execute failed: Data too long for column 'SUBJECT_ID' at row 279 at /orthomclSoftware-v2.0.9/bin/orthomclLoadBlast line 39, <F> line 12.`
  Can you give me some advice?
  Thanks,

**Comment by apetkau** [comment]
Hello @U201412486, how long is the combination of your fasta file name and fasta record header name? The default OrthoMCL database schema limits you to 60 characters total for both of them (https://github.com/apetkau/orthomclsoftware-custom/blob/master/bin/orthomclInstallSchema#L50). You will likely have to use shorter file/fasta record names.

**Comment by U201412486** [comment]
Thanks.You advice  helps.
   sun,

**Comment by apetkau** [comment]
No problem. I'm glad I could help.
