### ISSUE TITLE
Questions about OrthoMCL software 

### ISSUE THREAD

**Issue by lanlan0210** [apetkau/orthomcl-pipeline#35]
Hi，I met a mistake, how can I fix it? Thanks！！！                                         
/orthomcl/orthomcl-pipeline-master/scripts/nml_parse_orthomcl.pl -i  ./groups.txt  -g genome-groups.txt -s --draw -o orthomcl-stats.txt  --genes          (What is the file for the -g parameter? -g : A CSV file that contains list of groups to view their ortholog groups. How do I get this CSV file.Is it a generated file or a file that needs to be configured. ) Thank you very much

**Comment by apetkau** [comment]
Hello @zhouguilan. The file for the `-g` parameter is a special file that you have to construct yourself to divide your genomes into the groups you wish to see in the venn diagram.

```
nepal: VC-25,VC-26,VC-14
haiti: 2010EL-1749,2010EL-1786,2010EL-1796,2010EL-1798,2011EL-2317,2012V-1001,\
3554-08,VC-10,VC-15,VC-18,VC-19,VC-1,VC-6
c6706: C6706
```

Please refer to https://github.com/apetkau/microbial-informatics-2014/tree/master/labs/orthomcl#step-8-venn-diagram-of-orthologs for more information.
