### ISSUE TITLE
Warning: some tables exist already in database dbi:mysql:wuorthomcl:localhost:mysql_local_infile, user=liu, database_name=orthomcl. Do you want to remove (y/n)?

### ISSUE THREAD

**Issue by wuxiaopei0509** [apetkau/orthomcl-pipeline#36]
Hi
When I run orthomcl pipeline ,it occured printed what the title shows and stopped? Can you tell me how to solve it?
Thanks a lot!

**Comment by apetkau** [comment]
Hello @wuxiaopei0509. This normally means you have run the orthomcl pipeline before using the same database and there are still old tables in the database left over. You can either choose to delete them to make room for new tables (by choosing `y`) or not to delete them, at which point you'll need to run the orthomcl pipeline with a different (and empty) database.

**Comment by wuxiaopei0509** [comment]
It's very kind of you . the issue above have been already  soluted.Now it occured another problem,the program stopped at Stage 10: Load Blast Results.detail information as follows:
Error executing command: /home/wuxiaopei/software/orthomclSoftware-v2.0.9/bin/orthomclLoadBlast "/home/wuxiaopei/software/orthomcl-pipeline-master/orthomcl.conf" "/home/wuxiaopei/homolog/longest_protein_for_homolog_species/50aa_protein_gene_cluster-orthomcl/blast_load/similarSequences.txt" 1>/home/wuxiaopei/homolog/longest_protein_for_homolog_species/50aa_protein_gene_cluster-orthomcl/log/10.orthomclLoadBlast.out.log 2>/home/wuxiaopei/homolog/longest_protein_for_homolog_species/50aa_protein_gene_cluster-orthomcl/log/10.orthomclLoadBlast.err.log. See logs /home/wuxiaopei/homolog/longest_protein_for_homolog_species/50aa_protein_gene_cluster-orthomcl/log/10.orthomclLoadBlast.out.log and /home/wuxiaopei/homolog/longest_protein_for_homolog_species/50aa_protein_gene_cluster-orthomcl/log/10.orthomclLoadBlast.err.log

I check the 10.orthomclLoadBlast.err.log and it says‘’DBD::mysql::st execute failed: Data too long for column 'SUBJECT_ID' at row 4 at /home/wuxiaopei/software/orthomclSoftware-v2.0.9/bin/orthomclLoadBlast line 39, <F> line 12.‘’ 
what does it mean ?  Thanks a lot!

**Comment by wuxiaopei0509** [comment]
Hi,apetkau
the above problem above have also been sloved ,unfortunately I met another problem at the filterfasta process, I check the filterFasta.log and found following:

The ID on def line '>R.chinensis|RC0G0000100' is missing the prefix 'chinensis|' 'R.chinensis'

and my fasta seq ID is like 'RC0G0000100' ,so I have no idea where ir the problem. 

So can you help me ? Thanks.

**Comment by apetkau** [comment]
Hello @wuxiaopei0509, this issue is likely caused by your fasta files having a period `.` in there name other than the extension `.fasta`. That is, `R.` at the beginning of the file is messing up OrthoMCL.

You will likely have to rename the fasta files to remove the period `.`

**Comment by wuxiaopei0509** [comment]
Hi, @apetkau ,I rename the fasta file and It can run now
Thank you !

**Comment by apetkau** [comment]
No problem.

**Comment by wuxiaopei0509** [comment]
sorry, @apetkau 
I error another problem ,it stopped at the load blast step ,the 10.orthomclLoadBlast.err.log said'DBD::mysql::st execute failed: Data too long for column 'SUBJECT_ID' at row 10 at /home/wuxiaopei/software/orthomclSoftware-v2.0.9/bin/orthomclLoadBlast line 39, <F> line 12.
what does the 'SUBJECT_ID' mean? and How can I resolve it?
Thank you .apetkau
xiaopeiwu
