### ISSUE TITLE
 containing non-protein alphabet (dna)

### ISSUE THREAD

**Issue by U201412486** [apetkau/orthomcl-pipeline#37]
Hi,
  When I run the orthomcl-pipeline,it report the error below.
  `sicum.fasta contains a sequence (lycopersicum|XP_025883763.1) containing non-protein alphabet (dna) at /scripts/orthomcl-pipeline.pl line 361, <GEN5> line 22972.
`
And the sequence of XP_025883763.1 is `NNNNNNNNNNNTNTNNNTNNNNNNNTNNNNNNNDNNNDNNDNNNNNNNDNNNNNNNDTNNNNNNDNNNDDDNNDNNDNNNNNNNNNDNNNTNNNTNNNNNNNNNTNNTNNNNNNNNNNNTTTTTNNTNTNNTNNNNTNNNTNNNNNNNKNNNKNNNNNNTNTNNNNNNNNTNTNNNNNNNTYNNNNNNNTNNNNTNNNTNNNNNNNNNSNNSNNNNNNNDDDDDDNNDNNNNNDNNNNNNNDDNNNNNNNNNNNSNSNNSNNSSSSSSNNNNNNNNNNNDDDDDNNNNNNNNNKNNKNNNNNDDDDDNNNDNNNNNNNNNNNNDNNDNNNNDNNNDNYNDNNDDNNNNNNNNNNNSNNSNNNN`
Why not is identified by the software ?
Thanks,

**Comment by apetkau** [comment]
Hello @U201412486, please try pulling the code `git pull` and running again.

This issue was fixed in the `development` branch (PR #30 ), but it was not merged into `master`. I have fixed this now.

**Comment by U201412486** [comment]
I am not familiar with the code `git pull`.
Can you show me an example ?
many Thanks,

**Comment by apetkau** [comment]
`git pull` is run when you're in the directory containing the orthomcl pipeline software. It will update to the latest version of the code.

Or, you can also reinstall the orthomcl-pipeline the same as you installed it before and the code should be updated.

**Comment by U201412486** [comment]
Thanks you.

**Comment by apetkau** [comment]
No problem.

**Comment by wuxiaopei0509** [comment]
I have the same error and I reinstall the pipeline ,however it also orrured the warning. have you resolved it ?

**Comment by apetkau** [comment]
Can you run `git rev-parse HEAD` which should tell you the git commit (version of code) you are using? It should report `4ecd63b4215f6262a0f2215b8fedbba869119fc8` which is the latest code.

**Comment by wuxiaopei0509** [comment]
Thank you ,apetkau
I have resloved the problem and it runa normally now.

**Comment by apetkau** [comment]
That's great.
