### ISSUE TITLE
The network links of virtual machine containing the OrthoMCL pipeline is broken.

### ISSUE THREAD

**Issue by Caizhaohui** [apetkau/orthomcl-pipeline#40]
Hello！
     @apetkau I want to download the pre-configured virtual machine appliance: https://share.corefacility.ca/public.php?service=files&t=f8781e48fac7c28de3830f20e9f92bf5. But this link is broken, I can not download the virtual machine containing a pre-installed version of the OrthoMCL pipeline. Can you update this link so that I can use the OrthoMCL pipeline successfully. 

Best regards
Zhaohui Cai

**Comment by apetkau** [comment]
Hello @Caizhaohui , thank you for pointing this out. Unfortunately the virtual machine is no longer available. However, you can install the OrthoMCL pipeline yourself by following the instructions here <https://github.com/apetkau/orthomcl-pipeline/blob/master/INSTALL.md>.
