### ISSUE TITLE
failing tests with t/test.pipeline.pl

### ISSUE THREAD

**Issue by ggoodstudydaydayup** [apetkau/orthomcl-pipeline#42]
Hi,
    When I want to test the pipeline, I met a problem.
    "Can't load '/data/liuyu/Software/miniconda3/envs/LTR_retriever/lib/site_perl/5.26.2/x86_64-linux-thread-multi/auto/List/Util/Util.so' for module List::Util: /data/liuyu/Software/miniconda3/envs/LTR_retriever/lib/site_perl/5.26.2/x86_64-linux-thread-multi/auto/List/Util/Util.so: undefined symbol: Perl_drand48_r at /data/liuyu/Software/miniconda3/envs/LTR_retriever/lib/site_perl/5.26.2/x86_64-linux-thread-multi/XSLoader.pm line 96."
    Could you please give me some advice?
Thanks in advance.
Liu

**Comment by apetkau** [comment]
Hello @ggoodstudydaydayup , did you install the Perl dependencies using `conda` or `cpanm`? If you used `conda` could you instead try using `cpanm`. It looks like there could be a mismatch between the complied C libraries for some of the Perl modules and the Perl version.

**Comment by ggoodstudydaydayup** [comment]
Thanks for your advice ! @apetkau
