### ISSUE TITLE
error in step 8: orthomclBlastParser blastresult compliantFasta > similarSequences.txt

### ISSUE THREAD

**Issue by lyn320** [apetkau/orthomcl-pipeline#48]
here are my codes:
#! /bin/bash
#SBATCH -J processdata.sh
#SBATCH -p cast
#SBATCH -N 1
#SBATCH --ntasks=1
#SBATCH --mem=48gb
#SBATCH --mail-type=ALL    
#SBATCH --mail-user=yning@cau.edu.cn 
module load OrthoMCL/2.0.9
orthomclBlastParser blastresult compliantFasta > similarSequences.txt
#end

and the slurm file shows:
couldn't find taxon for gene 'apis|J9JPJ9' at /apps/local/software/bioinformatics/OrthoMCL-2.0.9/bin/orthomclBlastParser line 105, <F> line 1.
here are my blastresult file in case you need:
(base) [qulujiang@master orthomcl]$ head blastresult
fin|TRINITY_DN10008_c0_g1_i2.p1	apis|J9JPJ9	31.868	182	115	5	16	192	53	230	6.72e-20	91.7
fin|TRINITY_DN10008_c0_g1_i2.p1	gpap|GPPI003973	20.859	163	120	5	35	192	70	228	1.07e-10	66.2

as you can see , apis|J9JPJ9 is the object ID of the first gene in my input file,so  it just stuck here ,could you tell me how to fix the issue so i can move to the next step..
thanks a lot!

**Comment by lyn320** [comment]
i found the problem: forgot to put the OrthoMCL DB file( aa_seqs_OrthoMCL-6.10.fasta ) in the compliantFasta folder.

**Comment by apetkau** [comment]
I'm glad you were able to solve it.
