### ISSUE TITLE
Wrong syntax in scripts/orthomcl-pipeline.pl at line 294.

### ISSUE THREAD

**Issue by moshimoshimo1211** [apetkau/orthomcl-pipeline#9]
The warning message 'Odd number of elements ...' is known issue, but no problem in OrthoMCL running as mentioned in previous post.
I had also ignored this warning message in Ubuntu14.04(perl[v5.18.2]) environment because running properly.

But OrthoMCL running error occurs after upgrading Ubuntu16.04(perl[v5.22.1]) environment.
I diagnosed this error and figured out error causes in scripts/orthomcl-pipeline.pl at line 294.

***** scripts/orthomcl-pipeline.pl at line 294 *****
Before: Bio::SeqIO->new(-file => $file_path, 'Fasta')
After:  Bio::SeqIO->new(-file => $file_path, -format => 'Fasta')

After modifying line 294 as above, OrthoMCL runnning properly with no warning message.
This wrong syntax causes warning message 'Odd number of elements ...' and critical error in my Ubuntu16.04(perl[v5.22.1]) environment.

Can you please modify scripts/orthomcl-pipeline.pl at line 294 as mentioned above?

Yuki

**Comment by apetkau** [comment]
Hello Yuki,

Thanks for brining this up and giving a fix.  It's been merged in #10.

Let me know if you have any more issues,

Aaron
